"""tambah semua

Revision ID: 7acec800f80b
Revises: 
Create Date: 2026-02-24 11:48:32.855735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7acec800f80b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_survey_harian_active', sa.Boolean(), nullable=False),
    sa.Column('is_survey_mingguan_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('kode', sa.String(length=50), nullable=True),
    sa.Column('kelas', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('kode')
    )
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('record_siswa_harian',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('bahagia', sa.Integer(), nullable=False),
    sa.Column('semangat', sa.Integer(), nullable=False),
    sa.Column('fokus', sa.Integer(), nullable=False),
    sa.Column('bertenaga', sa.Integer(), nullable=False),
    sa.Column('stress', sa.Integer(), nullable=False),
    sa.Column('dukungan_teman', sa.Integer(), nullable=False),
    sa.Column('dukungan_guru', sa.Integer(), nullable=False),
    sa.Column('aman', sa.Integer(), nullable=False),
    sa.Column('rasakan', sa.String(), nullable=True),
    sa.Column('skor', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('record_siswa_mingguan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('bahagia', sa.Integer(), nullable=False),
    sa.Column('semangat', sa.Integer(), nullable=False),
    sa.Column('beban', sa.Integer(), nullable=False),
    sa.Column('cemas', sa.Integer(), nullable=False),
    sa.Column('bantuan_guru', sa.Integer(), nullable=False),
    sa.Column('menghargai', sa.Integer(), nullable=False),
    sa.Column('aman', sa.Integer(), nullable=False),
    sa.Column('bullying', sa.Integer(), nullable=True),
    sa.Column('desc_bullying', sa.String(), nullable=True),
    sa.Column('tidur', sa.String(), nullable=False),
    sa.Column('kehadiran', sa.String(), nullable=False),
    sa.Column('open_question', sa.String(length=200), nullable=True),
    sa.Column('skor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record_siswa_mingguan')
    op.drop_table('record_siswa_harian')
    op.drop_table('password_reset_tokens')
    op.drop_table('note')
    op.drop_table('users')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
